<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VicdeMac.local" ignored="0" name="sqProductList" tests="1" failures="1" timestamp="07 Aug 2020 08:57:43 GMT" time="32.175" errors="0">
  <testcase name="SqProductList" time="21.969" classname="test.SqProductList">
    <failure type="java.lang.AssertionError" message="检查点不通过 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 检查点不通过 expected [true] but found [false]
	at test.SqProductList.SqProductList(SqProductList.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- SqProductList -->
</testsuite> <!-- sqProductList -->
